stages:
  - build
  - deploy

variables:
  PROD_BUCKET: s3://lgea-crm-admin
  DEV_BUCKET: s3://lgea-crm-admin-dev

#FOR DEV
build:dev:
  image: node:10-stretch-slim
  stage: build
  except:
    # triggers on every branch, except master
    - master
  script:
    # Install dependencies
    - npm ci
    # Build App
    - npm run build
  artifacts:
    paths:
      # Build folder
      - dist/
    expire_in: 7 days

deploy:dev:
  image: python:3.6-slim
  stage: deploy
  except:
    # triggers on every branch, except master
    - master
  script:
    - pip install awscli
    - aws s3 sync ./dist ${DEV_BUCKET}
  dependencies:
    - build:dev

# FOR PRODUCTION
build:prod:
  image: node:10-stretch-slim
  stage: build
  only:
    # only trigger this step on master branch
    - master
  script:
    # Install dependencies
    - npm ci
    # Build App
    - npm run build
  artifacts:
    paths:
      # Build folder
      - dist/
    expire_in: 7 days

deploy:prod:
  image: python:3.6-slim
  stage: deploy
  only:
    # only trigger this step on master branch
    - master
  script:
    - pip install awscli
    - aws s3 sync ./dist ${PROD_BUCKET}
  dependencies:
    - build:prod